# Generated by Django 4.1.7 on 2023-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=25, verbose_name='ресурс')),
                ('time', models.CharField(default='', max_length=50, verbose_name='время публикации')),
                ('links', models.CharField(default='', max_length=10000, verbose_name='ссылки в публикации')),
                ('text_content', models.CharField(default='', max_length=10000, null=True, verbose_name='публикация')),
            ],
        ),
    ]
